services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    volumes:
      - ./test_rag/doc.html:/app/test_rag/doc.html:ro
    restart: always

